import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM,VirtualConsole} from 'jsdom';
const html=(await readFile(new URL('../index.html',import.meta.url),'utf8')).replace('<script type="module">','<script>');
function createApp(saved){
  const errors=[],console=new VirtualConsole();
  console.on('jsdomError',e=>{if(!e.message.includes('Not implemented: navigation'))errors.push(e.message);});
  const dom=new JSDOM(html,{url:'https://controlpublicidad.example.invalid/',runScripts:'dangerously',virtualConsole:console,beforeParse(w){
    w.structuredClone=structuredClone;
    w.scrollTo=()=>{};
    w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
    w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
    if(saved)w.localStorage.setItem('controlpublicidad-screens-v1',saved);
  }});
  const document=dom.window.document;
  const q=s=>{const el=document.querySelector(s);assert.ok(el,'Missing '+s);return el;};
  const click=s=>q(s).click();
  const change=(s,value)=>{const el=q(s);el.value=value;el.dispatchEvent(new dom.window.Event('change',{bubbles:true}));};
  const input=(s,value)=>{const el=q(s);el.value=value;el.dispatchEvent(new dom.window.Event('input',{bubbles:true}));};
  const submit=s=>q(s).dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
  const login=()=>{submit('#login-form');input('#login-code','123456');submit('#login-form');};
  return {dom,document,errors,q,click,change,input,submit,login,close:()=>dom.window.close()};
}
test('access demo rejects wrong code and opens dashboard with correct code',()=>{
  const a=createApp();a.submit('#login-form');a.input('#login-code','000000');a.submit('#login-form');
  assert.match(a.q('#login-error').textContent,/123456/);
  a.input('#login-code','123456');a.submit('#login-form');
  assert.match(a.q('h1').textContent,/Todo en su lugar/);
  assert.deepEqual(a.errors,[]);a.close();
});
test('user search, edit, invitations, hierarchy and role scope operate through the screens',()=>{
  const a=createApp();a.login();a.click('[data-nav="users"]');
  assert.equal(a.document.querySelectorAll('tbody tr').length,10);
  a.input('#user-search','Sofía');
  assert.equal(a.document.querySelectorAll('tbody tr').length,1);
  a.click('[data-action="edit-user"][data-id="m4"]');
  a.input('#edit-name','Sofía demo');a.submit('#edit-user-form');
  assert.match(a.q('tbody').textContent,/Sofía demo/);
  a.input('#user-search','');a.click('[data-action="invite-user"]');
  a.input('#invite-name','Nueva coordinadora demo');a.submit('#invite-form');
  assert.match(a.q('#dialog-title').textContent,/Invitación preparada/);
  a.click('[data-action="close-dialog"]');
  assert.equal(a.document.querySelectorAll('tbody tr').length,11);
  a.change('#demo-role','l1');a.click('[data-nav="users"]');
  assert.doesNotMatch(a.q('tbody').textContent,/Carlos Vega|Pablo Ruiz/);
  assert.equal(a.document.querySelectorAll('[data-action="edit-user"][data-id="m4"]').length,0);
  assert.equal(a.document.querySelectorAll('[data-action="edit-user"][data-id="m2"]').length,1);
  assert.equal(a.q("#users-table").open,false);
  assert.match(a.q('.tree').textContent,/Diego Méndez/);
  a.change('#demo-role','c1');a.click('[data-nav="users"]');
  assert.equal(a.document.querySelectorAll('tbody tr').length,3);
  assert.doesNotMatch(a.q('tbody').textContent,/Valeria Cruz/);
  assert.deepEqual(a.errors,[]);a.close();
});
test('campaign form, evidence filters, map and media details remain connected',()=>{
  const a=createApp();a.login();a.click('[data-action="new-campaign"]');
  a.input('#campaign-name','Campaña demo');a.input('#campaign-location','Morelia');a.change('#campaign-leader','l1');
  a.q('[name="types"][value="lona"]').checked=true;a.q('[name="types"][value="barda"]').checked=true;a.submit('#campaign-form');
  assert.equal(a.document.querySelectorAll('.campaign-card').length,4);
  a.click('[data-nav="evidence"]');a.change('#filter-campaign','p2');
  assert.equal(a.document.querySelectorAll('.evidence-card').length,4);
  a.click('[data-nav="map"]');assert.equal(a.document.querySelectorAll('.pin').length,4);
  a.click('.pin');assert.match(a.q('#dialog-title').textContent,/Registro/);
  assert.match(a.q('#modal').textContent,/GPS de ejemplo/);
  a.click('[data-action="close-dialog"]');
  a.change('#filter-from','2026-10-06');a.change('#filter-to','2026-10-06');
  assert.equal(a.document.querySelectorAll('.pin').length,0);
  assert.deepEqual(a.errors,[]);a.close();
});
test('capture enforces limits, restores draft, seals and simulates one-time sync',()=>{
  let a=createApp();a.login();a.change('#demo-role','f1');
  assert.equal(a.document.querySelectorAll('.sidebar .nav-link').length,2);
  assert.equal(a.document.querySelectorAll('[data-nav="users"]').length,0);
  a.change('[name="capture-type"][value="lona"]','lona');a.q('[name="capture-type"][value="lona"]').checked=true;
  for(let i=0;i<10;i++)a.click('[data-action="add-media"][data-kind="photo"]');
  assert.ok(a.q('[data-action="add-media"][data-kind="photo"]').disabled);
  for(let i=0;i<3;i++)a.click('[data-action="add-media"][data-kind="video"]');
  assert.ok(a.q('[data-action="add-media"][data-kind="video"]').disabled);
  assert.equal(a.document.querySelectorAll('.thumb').length,13);
  a.input('#capture-notes','Nota persistida de ejemplo.');
  const saved=a.dom.window.localStorage.getItem('controlpublicidad-screens-v1');a.close();
  a=createApp(saved);a.login();a.change('#demo-role','f1');
  assert.equal(a.document.querySelectorAll('.thumb').length,13);
  assert.equal(a.q('#capture-notes').value,'Nota persistida de ejemplo.');
  assert.ok(!a.q('[data-action="seal-record"]').disabled);
  a.click('[data-action="seal-record"]');assert.match(a.q('.capture-success').textContent,/Registro demo guardado/);
  a.click('[data-nav="sync"]');
  assert.equal(a.document.querySelectorAll('.sync-row .pill.amber').length,1);
  a.click('[data-action="sync"]');
  assert.ok(a.q('[data-action="sync"]').disabled);
  a.click('.sync-row [data-action="record-detail"]');
  assert.equal(a.document.querySelectorAll('.detail-media-tabs button').length,13);
  a.click('[data-action="record-media"][data-seq="11"]');
  assert.match(a.q('.media-placeholder').textContent,/Video de ejemplo/);
  assert.equal(a.document.querySelectorAll('#modal [data-action="edit-record"]').length,0);
  assert.deepEqual(a.errors,[]);a.close();
});
test('people tree is primary, filters keep ancestors, and profile totals include descendants',()=>{
  const a=createApp();a.login();a.click('[data-nav="users"]');
  assert.equal(a.q('#users-table').open,false);
  assert.equal(a.q('[data-branch="m1"]').open,true);assert.equal(a.q('[data-branch="m2"]').open,false);
  a.click('.tree [data-action="user-detail"][data-id="m1"]');
  assert.equal(a.q('[data-total="records"]').textContent,'14');
  assert.equal(a.q('[data-total="people"]').textContent,'6');
  a.click('[data-action="close-dialog"]');a.input('#user-search','Sofía');
  assert.match(a.q('.tree').textContent,/Mariana Torres/);assert.match(a.q('.tree').textContent,/Diego Méndez/);
  assert.doesNotMatch(a.q('.tree').textContent,/Elena García|Valeria Cruz/);
  assert.equal(a.q('[data-branch="m2"]').open,true);
  a.q('#users-table').open=true;assert.equal(a.document.querySelectorAll('tbody tr').length,1);
  assert.deepEqual(a.errors,[]);a.close();
});
test('manual creation, profile deactivation and reactivation preserve sample users',()=>{
  const a=createApp();a.login();a.click('[data-nav="users"]');a.click('[data-action="new-user"]');
  a.input('#manual-name','Colaborador nuevo');a.input('#manual-contact','nuevo@example.invalid');a.change('#manual-role','collaborator');
  a.change('#manual-parent','m2');a.submit('#manual-user-form');
  const saved=JSON.parse(a.dom.window.localStorage.getItem('controlpublicidad-screens-v1')).data;
  const u=saved.users.find(u=>u.contact==='nuevo@example.invalid'),m=saved.memberships.find(m=>m.userId===u.id);
  assert.equal(m.parentId,'m2');assert.equal(saved.users.length,11);
  a.click('.tree [data-action="user-detail"][data-id="'+m.id+'"]');a.click('[data-action="deactivate-user"]');a.submit('#edit-user-form');
  a.click('.tree [data-action="user-detail"][data-id="'+m.id+'"]');a.click('#modal [data-action="edit-user"]');
  a.change('#edit-status','active');a.input('#edit-name','Nombre modificado');a.submit('#edit-user-form');
  assert.match(a.q('.tree').textContent,/Nombre modificado/);
  assert.match(a.q('.tree').textContent,/Sofía López|Mariana Torres/);
  assert.deepEqual(a.errors,[]);a.close();
});
test('admin moves collaborator to another leader without relocating historical evidence',()=>{
  const a=createApp();a.login();a.click('[data-nav="users"]');a.click('.tree [data-action="user-detail"][data-id="m4"]');
  a.click('[data-action="move-user"]');a.change('#move-parent','m8');a.submit('#move-user-form');
  const saved=JSON.parse(a.dom.window.localStorage.getItem('controlpublicidad-screens-v1')).data;
  const old=saved.memberships.find(m=>m.id==='m4'),next=saved.memberships.find(m=>m.userId==='f1'&&m.status==='active');
  assert.equal(old.status,'transferred');assert.equal(old.parentId,'m2');assert.equal(next.parentId,'m8');assert.equal(next.campaignId,'p2');
  assert.ok(saved.records.filter(r=>r.membershipId==='m4').every(r=>r.campaignId==='p1'));
  a.change('#demo-role','l2');a.click('[data-nav="users"]');
  assert.match(a.q('.tree').textContent,/Sofía López/);
  a.click('.tree [data-action="user-detail"][data-id="'+next.id+'"]');
  assert.equal(a.q('[data-total="records"]').textContent,'0');assert.equal(a.document.querySelectorAll('#modal [data-action="move-user"]').length,0);
  assert.deepEqual(a.errors,[]);a.close();
});
