package com.controlpublicidad.app;

import android.app.*;
import android.graphics.Color;
import android.view.View;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Native administration, with the same forms for local tests and a connected server. */
public final class AdminPage {
 public interface Host{void create(String path,JSONObject input,Runnable saved,Runnable failed);void error(Exception error);}
 private final Activity activity;private final JSONObject data,actor;private final boolean remote;private final RecordStore store;private final Host host;
 public AdminPage(Activity activity,JSONObject data,JSONObject actor,boolean remote,RecordStore store,Host host){this.activity=activity;this.data=data;this.actor=actor;this.remote=remote;this.store=store;this.host=host;}
 public void show(LinearLayout body)throws Exception{
  if(!TeamPolicy.manages(actor)){body.addView(Ui.text(activity,"Este perfil no tiene permiso para administrar equipos.",16,Ui.MUTED));return;}
  boolean admin="admin".equals(actor.optString("role"));body.addView(Ui.title(activity,admin?"Administración":"Mi equipo"));body.addView(Ui.text(activity,remote?"Las altas requieren conexión y autorización del servidor.":"Prueba local · usuarios y campañas se guardan cifrados en este teléfono.",14,Ui.MUTED));
  LinearLayout actions=Ui.card(activity);actions.addView(Ui.button(activity,"＋ Alta de usuario",this::userForm));if(admin)actions.addView(Ui.button(activity,"＋ Crear campaña",this::campaignForm));actions.addView(Ui.text(activity,admin?"Crea un líder y después asígnalo a una campaña. Cada campaña tiene un solo líder.":"Puedes dar de alta únicamente "+("leader".equals(actor.optString("role"))?"coordinadores":"colaboradores")+" dentro de tu propia rama.",13,Ui.MUTED));body.addView(actions);
  body.addView(Ui.title(activity,"Campañas y equipos"));List<JSONObject> scope=TeamPolicy.scoped(data,actor);JSONArray campaigns=data.getJSONArray("campaigns");
  for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.getJSONObject(i);List<JSONObject> members=new ArrayList<>();Set<String> ids=new HashSet<>();for(JSONObject m:scope)if(c.getString("id").equals(m.optString("campaignId"))){members.add(m);ids.add(m.getString("id"));}if(!admin&&members.isEmpty())continue;
   LinearLayout card=Ui.card(activity);card.addView(Ui.text(activity,c.getString("name"),18,Ui.INK));card.addView(Ui.text(activity,c.optString("location"),13,Ui.MUTED));JSONArray types=c.getJSONArray("types");List<String> names=new ArrayList<>();for(int j=0;j<types.length();j++)names.add(Policy.type(types.getString(j)));card.addView(Ui.text(activity,(types.length()>1?"Mixta · ":"")+String.join(" · ",names),13,Ui.GREEN));
   for(JSONObject m:members)if(m.isNull("parentId")||!ids.contains(m.optString("parentId")))branch(card,m,members,new HashSet<>());body.addView(card);
  }
  if(admin){Set<String> assigned=new HashSet<>();for(JSONObject m:scope)assigned.add(m.getString("userId"));JSONArray users=data.getJSONArray("users");LinearLayout free=Ui.card(activity);int n=0;for(int i=0;i<users.length();i++){JSONObject u=users.getJSONObject(i);if("leader".equals(u.optString("role"))&&!assigned.contains(u.getString("id"))&&!u.optBoolean("deleted")){if(n++==0)free.addView(Ui.text(activity,"Líderes sin campaña",18,Ui.INK));Button b=Ui.button(activity,u.getString("name"),()->person(u,null));Ui.secondary(activity,b);free.addView(b);}}if(n>0)body.addView(free);}
 }
 private String name(JSONObject member)throws Exception{JSONObject u=Policy.find(data.getJSONArray("users"),"id",member.getString("userId"));String display=member.isNull("displayName")?"":member.optString("displayName");return display.trim().isEmpty()?(u==null?"Usuario":u.optString("name","Usuario")):display;}
 private int color(String role){return "leader".equals(role)?Color.rgb(38,105,197):"coordinator".equals(role)?Ui.GREEN:Color.rgb(167,122,0);}
 private String initials(String name){String[] parts=name.trim().split("\\s+");return name.isEmpty()?"?":parts[0].substring(0,1)+(parts.length>1?parts[parts.length-1].substring(0,1):"");}
 private void branch(LinearLayout parent,JSONObject m,List<JSONObject> members,Set<String> visited)throws Exception{
  if(!visited.add(m.getString("id")))return;List<JSONObject> children=new ArrayList<>();for(JSONObject child:members)if(m.getString("id").equals(child.optString("parentId")))children.add(child);
  LinearLayout row=Ui.row(activity),nested=Ui.column(activity);nested.setPadding(Ui.dp(activity,14),0,0,0);nested.setVisibility(View.GONE);String name=name(m),role=m.getString("role"),status=m.getString("status");
  TextView badge=Ui.text(activity,initials(name),14,Color.WHITE);badge.setGravity(android.view.Gravity.CENTER);badge.setBackground(Ui.shape(color(role),Ui.dp(activity,12),0));if(!"active".equals(status)){badge.setText(initials(name)+" ╱");badge.setTextColor(Color.rgb(255,150,150));}row.addView(badge,new LinearLayout.LayoutParams(Ui.dp(activity,44),Ui.dp(activity,44)));
  Button label=Ui.button(activity,(children.isEmpty()?"":"▸ ")+name+"\n"+Policy.role(role)+("active".equals(status)?"":" · Inactivo"),()->{if(children.isEmpty()){try{JSONObject u=Policy.find(data.getJSONArray("users"),"id",m.getString("userId"));person(u,m);}catch(Exception e){host.error(e);}}else{boolean open=nested.getVisibility()==View.VISIBLE;nested.setVisibility(open?View.GONE:View.VISIBLE);}});Ui.secondary(activity,label);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));Button view=Ui.button(activity,"Ver",()->{try{person(Policy.find(data.getJSONArray("users"),"id",m.getString("userId")),m);}catch(Exception e){host.error(e);}});Ui.secondary(activity,view);view.setContentDescription("Ver información de "+name);row.addView(view,new LinearLayout.LayoutParams(Ui.dp(activity,62),-2));parent.addView(row);for(JSONObject child:children)branch(nested,child,members,visited);if(!children.isEmpty())parent.addView(nested);
 }
 private void person(JSONObject user,JSONObject member){try{String display=member==null?user.getString("name"):name(member);String text=Policy.role(user.getString("role"))+"\n"+user.optString("contact")+"\n"+(member==null?"Sin campaña asignada":"active".equals(member.optString("status"))?"Activo":"Inactivo");
   if(member!=null){List<JSONObject> scope=TeamPolicy.scoped(data,actor);Set<String> ids=new HashSet<>();ids.add(member.getString("id"));boolean change=true;while(change){change=false;for(JSONObject m:scope)if(ids.contains(m.optString("parentId"))&&ids.add(m.getString("id")))change=true;}int records=0,photos=0,videos=0;List<JSONObject> evidence=new ArrayList<>();
    if(remote){JSONArray all=data.optJSONArray("records");if(all!=null)for(int i=0;i<all.length();i++)evidence.add(all.getJSONObject(i));}else{Set<String> people=new HashSet<>();for(JSONObject m:scope)if(ids.contains(m.getString("id")))people.add(m.getString("userId"));for(String uid:people)evidence.addAll(store.records("local-test|"+uid));}
    for(JSONObject r:evidence)if(ids.contains(r.optString("membershipId"))&&!"draft".equals(r.optString("status"))){records++;photos+=RecordStore.count(r,"photo");videos+=RecordStore.count(r,"video");}text+="\n\nEquipo: "+ids.size()+" personas\n"+records+" registros · "+photos+" fotos · "+videos+" videos"+(remote?"\nTotales de registros confirmados por el servidor.":"\nTotales guardados en este teléfono.");
   }new AlertDialog.Builder(activity).setTitle(display).setMessage(text).setPositiveButton("Cerrar",null).show();
  }catch(Exception e){host.error(e);}}
 private Spinner spinner(List<String> labels){Spinner s=new Spinner(activity);s.setAdapter(new ArrayAdapter<>(activity,android.R.layout.simple_spinner_dropdown_item,labels));s.setMinimumHeight(Ui.dp(activity,52));return s;}
 private void options(Spinner spinner,List<String> labels){spinner.setAdapter(new ArrayAdapter<>(activity,android.R.layout.simple_spinner_dropdown_item,labels));}
 private interface Save{JSONObject input()throws Exception;}
 private void form(String title,LinearLayout fields,String path,Save save){ScrollView scroll=new ScrollView(activity);scroll.addView(fields);AlertDialog dialog=new AlertDialog.Builder(activity).setTitle(title).setView(scroll).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{JSONObject value=save.input();Button b=dialog.getButton(AlertDialog.BUTTON_POSITIVE);b.setEnabled(false);host.create(path,value,()->dialog.dismiss(),()->{if(dialog.isShowing())b.setEnabled(true);});}catch(Exception e){host.error(e);}}));dialog.show();}
 private LinearLayout fields(){LinearLayout fields=Ui.column(activity);fields.setPadding(Ui.dp(activity,20),Ui.dp(activity,8),Ui.dp(activity,20),Ui.dp(activity,16));return fields;}
 private void userForm(){try{LinearLayout fields=fields();EditText name=Ui.input(activity,"Nombre completo"),contact=Ui.input(activity,"Correo o celular con +52");name.setSingleLine(true);contact.setSingleLine(true);fields.addView(name);fields.addView(contact);fields.addView(Ui.text(activity,"Nivel de usuario",14,Ui.INK));String[] roles=TeamPolicy.roles(actor);List<String> labels=new ArrayList<>();for(String role:roles)labels.add(Policy.role(role));Spinner role=spinner(labels);fields.addView(role);TextView hint=Ui.text(activity,"",14,Ui.MUTED);fields.addView(hint);Spinner parent=spinner(Collections.singletonList("Selecciona campaña y superior"));fields.addView(parent);List<JSONObject> available=new ArrayList<>();
   role.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> view){}public void onItemSelected(AdapterView<?> v,View view,int position,long id){try{String selected=roles[position];available.clear();available.addAll(TeamPolicy.parents(data,actor,selected,remote));List<String> names=new ArrayList<>();for(JSONObject p:available){JSONObject c=Policy.find(data.getJSONArray("campaigns"),"id",p.getString("campaignId"));names.add(c.getString("name")+" · "+name(p)+" ("+Policy.role(p.getString("role"))+")");}options(parent,names.isEmpty()?Collections.singletonList("No hay superiores activos disponibles"):names);parent.setVisibility("leader".equals(selected)?View.GONE:View.VISIBLE);hint.setText("leader".equals(selected)?"El administrador asignará a este líder al crear una campaña.":"Campaña y "+("coordinator".equals(selected)?"líder":"coordinador")+" al que pertenecerá");}catch(Exception e){host.error(e);}}});
   form("Alta de usuario",fields,"/api/users",()->{JSONObject input=new JSONObject().put("name",name.getText().toString()).put("contact",contact.getText().toString()).put("role",roles[role.getSelectedItemPosition()]);if(!"leader".equals(input.getString("role"))){int p=parent.getSelectedItemPosition();if(p<0||p>=available.size())throw new java.io.IOException("Crea primero un superior activo para este nivel.");JSONObject m=available.get(p);input.put("parentId",m.getString("id")).put("campaignId",m.getString("campaignId"));}return TeamPolicy.userInput(data,actor,input,remote);});
  }catch(Exception e){host.error(e);}}
 private void campaignForm(){try{LinearLayout fields=fields();EditText name=Ui.input(activity,"Nombre de campaña"),location=Ui.input(activity,"Ubicación");name.setSingleLine(true);location.setSingleLine(true);fields.addView(name);fields.addView(location);fields.addView(Ui.text(activity,"Líder general · uno por campaña",14,Ui.INK));List<JSONObject> leaders=new ArrayList<>();List<String> labels=new ArrayList<>();JSONArray users=data.getJSONArray("users");for(int i=0;i<users.length();i++){JSONObject u=users.getJSONObject(i);if("leader".equals(u.optString("role"))&&u.optBoolean("active",true)&&!u.optBoolean("deleted")){leaders.add(u);labels.add(u.getString("name"));}}Spinner leader=spinner(labels.isEmpty()?Collections.singletonList("Da de alta un líder primero"):labels);fields.addView(leader);fields.addView(Ui.text(activity,"Tipos permitidos · mixta al elegir dos o más",14,Ui.INK));String[] types={"lona","espectacular","barda"};CheckBox[] checks=new CheckBox[3];for(int i=0;i<3;i++){checks[i]=new CheckBox(activity);checks[i].setText(Policy.type(types[i]));checks[i].setMinHeight(Ui.dp(activity,46));fields.addView(checks[i]);}
   form("Crear campaña",fields,"/api/campaigns",()->{int p=leader.getSelectedItemPosition();if(p<0||p>=leaders.size())throw new java.io.IOException("Da de alta un líder primero.");JSONArray allowed=new JSONArray();for(int i=0;i<3;i++)if(checks[i].isChecked())allowed.put(types[i]);return TeamPolicy.campaignInput(data,actor,new JSONObject().put("name",name.getText().toString()).put("location",location.getText().toString()).put("leaderId",leaders.get(p).getString("id")).put("types",allowed));});
  }catch(Exception e){host.error(e);}}
}
