package com.controlpublicidad.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private RecordStore store;private JSONObject settings,data,actor;private String owner,tab="capture",draftId,permissionKind,permissionRecord;
 private LinearLayout body;private TextView progress;private EditText notes;private Runnable notesSave;private final Handler ui=new Handler(Looper.getMainLooper());
 private final ExecutorService io=Executors.newSingleThreadExecutor();private volatile boolean uploading=false,sealing=false;private String dayFilter="";
 private static final String WEB="https://controlpublicidad-pruebas.fidelrama.chatgpt.site/";
 @Override public void onCreate(Bundle state){super.onCreate(state);try{store=Vault.get(this);String recovery=Vault.recover(this);load();render();if(!recovery.isEmpty())notice("Recuperación",recovery);}catch(Exception e){fatal(e);}}
 private void load()throws Exception{
  settings=store.settings();boolean remote=settings.optBoolean("remote");
  if(remote){actor=settings.getJSONObject("user");data=settings.getJSONObject("data");}
  else{data=Vault.demo(this);actor=Policy.find(data.getJSONArray("users"),"id",settings.optString("demoUser","f1"));if(actor==null)throw new IOException("Perfil de prueba no disponible.");}
  owner=Vault.owner(settings);
 }
 private void render(){if(isFinishing()||isDestroyed())return;try{flushNotes();notes=null;draftId=null;load();LinearLayout root=Ui.column(this);
  LinearLayout header=Ui.row(this);header.setPadding(Ui.dp(this,18),Ui.dp(this,12),Ui.dp(this,18),Ui.dp(this,10));
  TextView icon=Ui.text(this,"CP",18,Color.WHITE);icon.setGravity(Gravity.CENTER);icon.setBackground(Ui.shape(Ui.GREEN,Ui.dp(this,12),0));icon.setContentDescription("ControlPublicidad, ir al inicio");icon.setOnClickListener(v->{tab="capture";render();});header.addView(icon,new LinearLayout.LayoutParams(Ui.dp(this,44),Ui.dp(this,44)));
  LinearLayout brand=Ui.column(this);brand.setPadding(Ui.dp(this,12),0,0,0);TextView name=Ui.text(this,"ControlPublicidad",19,Ui.INK);name.setTypeface(null,android.graphics.Typeface.BOLD);brand.addView(name);brand.addView(Ui.text(this,"Beta Android · 0.1.0",12,Ui.MUTED));header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));root.addView(header);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=Ui.column(this);body.setPadding(Ui.dp(this,18),Ui.dp(this,8),Ui.dp(this,18),Ui.dp(this,20));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=Ui.row(this);nav.setPadding(Ui.dp(this,12),Ui.dp(this,4),Ui.dp(this,12),Ui.dp(this,6));String[] labels={"Capturar","Mis envíos","Cuenta"},keys={"capture","records","account"};for(int i=0;i<3;i++){String key=keys[i];Button b=Ui.button(this,labels[i],()->{tab=key;dayFilter="";render();});if(!tab.equals(key))Ui.secondary(this,b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,Ui.dp(this,48),1);p.setMargins(Ui.dp(this,3),0,Ui.dp(this,3),0);nav.addView(b,p);}root.addView(nav);Ui.root(this,root);
  LinearLayout identity=Ui.card(this);String initials=initials(actor.getString("name"));int color="leader".equals(actor.optString("role"))?Color.rgb(38,105,197):"coordinator".equals(actor.optString("role"))?Ui.GREEN:"collaborator".equals(actor.optString("role"))?Color.rgb(193,145,12):Ui.MUTED;
  TextView who=Ui.text(this,initials+"   "+actor.getString("name")+" · "+Policy.role(actor.getString("role")),15,color);who.setTypeface(null,android.graphics.Typeface.BOLD);identity.addView(who);identity.addView(Ui.text(this,settings.optBoolean("remote")?"Cuenta del servidor · asignaciones guardadas para trabajar sin internet":"Perfil local de prueba · datos independientes del navegador",12,Ui.MUTED));body.addView(identity);
  progress=Ui.text(this,uploading?"Actualizando registros…":"",13,Ui.GREEN);body.addView(progress);
  if("capture".equals(tab))capturePage();else if("records".equals(tab))recordsPage();else accountPage();
 }catch(Exception e){error(e);}}
 private String initials(String name){String[] names=name.split(" ");return names[0].substring(0,1)+(names.length>1?names[names.length-1].substring(0,1):"");}
 private void capturePage()throws Exception{
  body.addView(Ui.title(this,"Nuevo registro"));if(!settings.optBoolean("remote"))body.addView(Ui.text(this,"Prueba local: estas tomas se conservan solo en este teléfono y no se subirán a cuentas reales.",14,Ui.MUTED));JSONObject draft=store.draft(owner);
  if(draft==null){List<JSONObject> options=Policy.assignments(data,actor,settings.optBoolean("remote"));
   if(options.isEmpty()){body.addView(Ui.text(this,"No tienes una asignación activa para capturar. El administrador puede consultar el panel web.",16,Ui.MUTED));return;}
   body.addView(Ui.text(this,"Elige una campaña para iniciar. Cada toma se conserva en este teléfono antes de enviarse.",15,Ui.MUTED));LinearLayout card=Ui.card(this);String[] names=new String[options.size()];for(int i=0;i<names.length;i++)names[i]=options.get(i).getJSONObject("campaign").getString("name");Spinner campaigns=new Spinner(this);campaigns.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));card.addView(campaigns,new LinearLayout.LayoutParams(-1,Ui.dp(this,56)));
   card.addView(Ui.button(this,"Crear registro",()->{try{JSONObject selected=options.get(campaigns.getSelectedItemPosition());store.create(owner,actor,selected.getJSONObject("campaign"),selected.getJSONObject("membership"),Vault.device(this,store));render();}catch(Exception e){error(e);}}));body.addView(card);return;
  }
  draftId=draft.getString("id");LinearLayout card=Ui.card(this);card.addView(Ui.text(this,draft.getString("campaignName"),18,Ui.INK));card.addView(Ui.text(this,"Borrador cifrado · "+shortId(draftId),12,Ui.MUTED));card.addView(Ui.text(this,"Tipo de evidencia",14,Ui.INK));RadioGroup types=new RadioGroup(this);types.setOrientation(RadioGroup.VERTICAL);JSONArray allowed=draft.getJSONArray("allowedTypes");
  for(int i=0;i<allowed.length();i++){String t=allowed.getString(i);RadioButton b=new RadioButton(this);b.setId(View.generateViewId());b.setTag(t);b.setText(Policy.type(t));b.setMinHeight(Ui.dp(this,46));b.setEnabled(!sealing);types.addView(b);if(t.equals(draft.getString("type")))b.setChecked(true);}card.addView(types);
  notes=Ui.input(this,"Notas del registro");notes.setMinLines(2);notes.setMaxLines(5);notes.setGravity(Gravity.TOP);notes.setFilters(new InputFilter[]{new InputFilter.LengthFilter(1000)});notes.setText(draft.getString("notes"));notes.setEnabled(!sealing);card.addView(notes);
  final String rid=draftId;final EditText field=notes;types.setOnCheckedChangeListener((g,id)->{RadioButton b=g.findViewById(id);if(b!=null)try{flushNotes();store.update(rid,(String)b.getTag(),field.getText().toString());}catch(Exception e){error(e);}});
  notes.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){if(notesSave!=null)ui.removeCallbacks(notesSave);notesSave=()->{try{JSONObject r=store.record(rid);store.update(rid,r.getString("type"),field.getText().toString());}catch(Exception e){error(e);}};ui.postDelayed(notesSave,400);}public void afterTextChanged(Editable e){}});
  int photos=RecordStore.count(draft,"photo"),videos=RecordStore.count(draft,"video");card.addView(Ui.text(this,photos+" / 10 fotografías     "+videos+" / 3 videos",15,Ui.GREEN));
  Button photo=Ui.button(this,"＋ Tomar fotografía",()->startCamera(rid,"photo"));photo.setEnabled(photos<10&&!sealing);card.addView(photo);Button video=Ui.button(this,"＋ Grabar video",()->startCamera(rid,"video"));Ui.secondary(this,video);video.setEnabled(videos<3&&!sealing);card.addView(video);
  addMedia(card,draft);JSONObject pending=store.pending();if(pending!=null&&rid.equals(pending.optString("recordId"))){card.addView(Ui.text(this,"Hay una captura interrumpida. Se conserva; vuelve a abrir la app para intentar recuperarla.",14,Color.rgb(158,76,34)));
   if(store.files.exists("recovery-"+pending.getString("id")+".bin")){Button archive=Ui.button(this,"Conservar aparte y continuar",()->new AlertDialog.Builder(this).setTitle("Conservar grabación interrumpida").setMessage("El archivo no se puede reproducir. Sus bytes quedarán cifrados para revisión y no se incluirán en el envío. Podrás continuar con las demás evidencias sin borrarlo.").setNegativeButton("Cancelar",null).setPositiveButton("Conservar aparte",(d,w)->{try{store.archiveInterrupted();render();}catch(Exception e){error(e);}}).show());Ui.secondary(this,archive);card.addView(archive);}
  }
  if(draft.optJSONArray("interrupted")!=null)card.addView(Ui.text(this,"Se conserva una grabación interrumpida aparte. No forma parte de los archivos que se enviarán.",13,Color.rgb(158,76,34)));
  card.addView(Ui.text(this,"Sellar fija el contenido y lo coloca en la cola de envío. La copia cifrada se conserva aunque falle internet.",13,Ui.MUTED));Button seal=Ui.button(this,sealing?"Verificando archivos…":"Sellar registro",()->confirmSeal(rid));seal.setEnabled(!sealing&&!uploading&&draft.getJSONArray("media").length()>0&&pending==null);card.addView(seal);body.addView(card);
 }
 private void flushNotes(){if(notesSave!=null){ui.removeCallbacks(notesSave);Runnable r=notesSave;notesSave=null;r.run();}}
 private void startCamera(String rid,String kind){try{flushNotes();JSONObject r=store.record(rid);if(!owner.equals(r.getString("owner")))throw new IOException("El borrador pertenece a otro perfil.");
  permissionRecord=rid;permissionKind=kind;List<String> permissions=new ArrayList<>();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.CAMERA);
  if("video".equals(kind)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.RECORD_AUDIO);
  if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){permissions.add(Manifest.permission.ACCESS_COARSE_LOCATION);permissions.add(Manifest.permission.ACCESS_FINE_LOCATION);}
  if(!permissions.isEmpty()){requestPermissions(permissions.toArray(new String[0]),110);return;}launchCamera();
 }catch(Exception e){error(e);}}
 private void launchCamera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){notice("Permiso de cámara","Activa Cámara en los permisos de ControlPublicidad para tomar fotografías.");return;}if("video".equals(permissionKind)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){notice("Permiso de micrófono","Activa Micrófono para grabar video.");return;}startActivityForResult(new Intent(this,CameraActivity.class).putExtra("recordId",permissionRecord).putExtra("kind",permissionKind),120);}
 @Override public void onRequestPermissionsResult(int c,String[] p,int[] r){super.onRequestPermissionsResult(c,p,r);if(c==110)launchCamera();}
 @Override protected void onActivityResult(int c,int r,Intent data){super.onActivityResult(c,r,data);if(c==120){try{String result=Vault.recover(this);render();if(!result.isEmpty())notice("Recuperación",result);}catch(Exception e){error(e);}}}
 private void confirmSeal(String rid){flushNotes();new AlertDialog.Builder(this).setTitle("Sellar y conservar registro").setMessage("Después de sellar no podrás modificar ni eliminar este registro. Se intentará enviar si tienes una cuenta del servidor; sin conexión quedará pendiente.").setNegativeButton("Revisar",null).setPositiveButton("Sellar",(d,w)->{sealing=true;render();io.execute(()->{try{store.seal(rid);ui.post(()->{sealing=false;tab="records";render();if(settings.optBoolean("remote"))sync();else notice("Registro guardado","El registro está sellado y cifrado en este teléfono. En el modo local de prueba no se envía a la nube.");});}catch(Exception e){ui.post(()->{sealing=false;render();error(e);});}});}).show();}
 private void recordsPage()throws Exception{
  body.addView(Ui.title(this,"Mis envíos"));List<JSONObject> all=store.records(owner);int pending=0,synced=0;for(JSONObject r:all){if("synced".equals(r.optString("status")))synced++;else if(!"draft".equals(r.optString("status")))pending++;}
  body.addView(Ui.text(this,pending+" pendientes · "+synced+" confirmados por servidor",15,Ui.GREEN));LinearLayout chart=Ui.card(this);chart.addView(Ui.text(this,"Evidencia por día",18,Ui.INK));chart.addView(Ui.text(this,"Fotografías y videos · toca una barra para ver el día",12,Ui.MUTED));DailyChartView graph=new DailyChartView(this,all,(day,label)->{dayFilter=day;render();Toast.makeText(this,label,Toast.LENGTH_LONG).show();});chart.addView(graph,new LinearLayout.LayoutParams(-1,Ui.dp(this,220)));body.addView(chart);
  Button update=Ui.button(this,uploading?"Actualizando…":"Actualizar a la nube",this::sync);update.setEnabled(!uploading);body.addView(update);
  if(!dayFilter.isEmpty()){body.addView(Ui.text(this,"Registros del "+dayFilter,15,Ui.GREEN));Button reset=Ui.button(this,"Ver todos los días",()->{dayFilter="";render();});Ui.secondary(this,reset);body.addView(reset);}
  if(all.isEmpty())body.addView(Ui.text(this,"Todavía no tienes registros en este perfil.",16,Ui.MUTED));
  for(JSONObject r:all){if(!dayFilter.isEmpty()&&!dayFilter.equals(DailyChartView.day(r)))continue;LinearLayout card=Ui.card(this);String status=r.getString("status");card.addView(Ui.text(this,r.getString("campaignName"),17,Ui.INK));card.addView(Ui.text(this,("draft".equals(status)?"Borrador":"synced".equals(status)?"Confirmado · registro "+r.optInt("number"):"Pendiente en este teléfono")+" · "+Policy.type(r.getString("type")),14,"synced".equals(status)?Ui.GREEN:Ui.MUTED));card.addView(Ui.text(this,RecordStore.count(r,"photo")+" fotos · "+RecordStore.count(r,"video")+" videos · "+format(r.optString("sealedAt",r.getString("createdAt"))),13,Ui.MUTED));if(!r.optString("lastError").isEmpty())card.addView(Ui.text(this,r.getString("lastError"),13,Color.rgb(158,76,34)));String id=r.getString("id");Button open=Ui.button(this,"draft".equals(status)?"Continuar borrador":"Ver evidencia",()->{if("draft".equals(status)){tab="capture";render();}else recordDialog(id);});Ui.secondary(this,open);card.addView(open);body.addView(card);}
 }
 private void recordDialog(String rid){try{JSONObject r=store.record(rid);LinearLayout card=Ui.column(this);card.setPadding(Ui.dp(this,18),Ui.dp(this,8),Ui.dp(this,18),Ui.dp(this,16));card.addView(Ui.text(this,r.getString("authorName"),16,Ui.INK));card.addView(Ui.text(this,Policy.type(r.getString("type"))+" · "+format(r.getString("sealedAt")),14,Ui.MUTED));card.addView(Ui.text(this,r.optString("notes"),15,Ui.INK));JSONObject d=r.getJSONObject("device");card.addView(Ui.text(this,d.getString("brand")+" · "+d.getString("model")+"\nInstalación: "+d.getString("installationId"),12,Ui.MUTED));addMedia(card,r);ScrollView scroll=new ScrollView(this);scroll.addView(card);new AlertDialog.Builder(this).setTitle(r.getString("campaignName")).setView(scroll).setPositiveButton("Cerrar",null).show();}catch(Exception e){error(e);}}
 private void addMedia(LinearLayout container,JSONObject record)throws Exception{
  JSONArray media=record.getJSONArray("media");for(int i=0;i<media.length();i++){JSONObject m=media.getJSONObject(i);String rid=record.getString("id"),mid=m.getString("id");String seq=String.valueOf(i+1);String name=record.getString("campaignName")+" - "+(record.optInt("number")>0?record.getInt("number"):"pendiente "+shortId(rid))+" - "+seq+("photo".equals(m.getString("kind"))?".jpg":".mp4");
   Button view=Ui.button(this,("photo".equals(m.getString("kind"))?"▧ ":"▷ ")+name,()->startActivity(new Intent(this,PreviewActivity.class).putExtra("recordId",rid).putExtra("mediaId",mid)));Ui.secondary(this,view);container.addView(view);container.addView(Ui.text(this,format(m.getString("capturedAt")),12,Ui.MUTED));JSONObject gps=m.optJSONObject("gps");
   if(gps==null)container.addView(Ui.text(this,"GPS no disponible en esta toma",12,Color.rgb(158,76,34)));
   else{TextView location=Ui.text(this,String.format(Locale.ROOT,"GPS %.6f, %.6f · precisión ±%.0f m ↗",gps.getDouble("lat"),gps.getDouble("lng"),gps.getDouble("accuracy")),13,Ui.GREEN);location.setMinHeight(Ui.dp(this,44));location.setOnClickListener(v->maps(gps));container.addView(location);}
  }
 }
 private void maps(JSONObject gps){try{open("https://www.google.com/maps/search/?api=1&query="+Uri.encode(gps.getDouble("lat")+","+gps.getDouble("lng")));}catch(Exception e){error(e);}}
 private void sync(){if(uploading)return;if(!settings.optBoolean("remote")||settings.optString("cookie").isEmpty()){notice("Conectar al servidor","Estos registros pertenecen a un perfil local de prueba y se conservarán en el teléfono. Para nuevos registros conectados, inicia sesión en Cuenta con la API móvil por HTTPS. La vista web de prueba todavía no recibe fotos ni videos reales.");return;}
  try{JSONObject connection=new JSONObject(settings.toString());String namespace=owner;uploading=true;render();io.execute(()->{int sent=0,failed=0;try{ApiClient api=new ApiClient(new ApiClient.HttpTransport(connection.getString("origin"),connection.getString("cookie"),connection.getString("csrf")));for(JSONObject r:store.records(namespace))if("pending".equals(r.optString("status"))){String rid=r.getString("id");try{JSONObject receipt=api.upload(store,r,text->ui.post(()->{if(progress!=null)progress.setText(text);}));store.received(rid,receipt);sent++;}catch(Exception e){store.error(rid,message(e));failed++;}}int done=sent,errors=failed;ui.post(()->{uploading=false;render();notice("Actualización",done+" registros confirmados. "+errors+" pendientes de reintentar. Las copias cifradas permanecen en el teléfono.");});}catch(Exception e){ui.post(()->{uploading=false;render();error(e);});}});
  }catch(Exception e){uploading=false;error(e);}
 }
 private void accountPage()throws Exception{
  body.addView(Ui.title(this,"Cuenta y conexión"));LinearLayout local=Ui.card(this);local.addView(Ui.text(this,"Perfiles de prueba",18,Ui.INK));local.addView(Ui.text(this,"Para probar cámara, GPS y trabajo sin internet. No verifican correo o teléfono y no comparten datos con el navegador.",14,Ui.MUTED));Button choose=Ui.button(this,"Elegir usuario de prueba",this::chooseDemo);Ui.secondary(this,choose);choose.setEnabled(!uploading&&!sealing);local.addView(choose);body.addView(local);
  LinearLayout server=Ui.card(this);server.addView(Ui.text(this,"Conectar API móvil",18,Ui.INK));server.addView(Ui.text(this,"Necesita un servidor HTTPS con entrega de códigos por correo o SMS. El alojamiento de la vista de prueba aún no ofrece este servicio.",14,Ui.MUTED));EditText origin=Ui.input(this,"https://servidor-ejemplo.mx");origin.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);origin.setSingleLine(true);origin.setText(settings.optString("origin",""));server.addView(origin);EditText contact=Ui.input(this,"Correo o celular con +52");contact.setSingleLine(true);contact.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);server.addView(contact);EditText code=Ui.input(this,"Código de 6 dígitos");code.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);code.setSingleLine(true);code.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});server.addView(code);
  Button request=Ui.button(this,"Solicitar código",()->{String endpoint=origin.getText().toString(),value=contact.getText().toString();network(()->{ApiClient.HttpTransport transport=new ApiClient.HttpTransport(endpoint,"","");JSONObject result=new ApiClient(transport).json("POST","/api/auth/request",new JSONObject().put("contact",value));ui.post(()->notice("Código de acceso",result.has("developmentCode")?"Servidor de desarrollo. Código de prueba: "+result.optString("developmentCode"):result.optString("message","Revisa tu correo o mensajes.")));});});request.setEnabled(!uploading&&!sealing);server.addView(request);
  Button login=Ui.button(this,"Verificar e iniciar sesión",()->{String endpoint=origin.getText().toString().trim(),value=contact.getText().toString().trim(),digits=code.getText().toString().trim();network(()->{ApiClient.HttpTransport transport=new ApiClient.HttpTransport(endpoint,"","");JSONObject result=new ApiClient(transport).json("POST","/api/auth/verify",new JSONObject().put("contact",value).put("code",digits));if(transport.newCookie.isEmpty())throw new IOException("El servidor no entregó una sesión.");ApiClient api=new ApiClient(new ApiClient.HttpTransport(endpoint,transport.newCookie,result.getString("csrf")));JSONObject bootstrap=api.json("GET","/api/bootstrap",null);if(!bootstrap.has("captureAssignments"))throw new IOException("Actualiza el servidor para habilitar la captura Android.");JSONObject next=store.settings();next.put("remote",true).put("origin",endpoint.replaceAll("/+$","")).put("cookie",transport.newCookie).put("csrf",result.getString("csrf")).put("user",result.getJSONObject("user")).put("data",bootstrap).put("expiresAt",result.optLong("expiresAt"));store.settings(next);ui.post(()->{tab="capture";render();notice("Sesión verificada","Tus asignaciones se guardaron cifradas para continuar sin internet.");});});});login.setEnabled(!uploading&&!sealing);server.addView(login);
  if(settings.optBoolean("remote")){server.addView(Ui.text(this,"Servidor: "+settings.getString("origin"),13,Ui.GREEN));Button refresh=Ui.button(this,"Actualizar asignaciones",()->{try{JSONObject old=new JSONObject(settings.toString());network(()->{ApiClient api=new ApiClient(new ApiClient.HttpTransport(old.getString("origin"),old.getString("cookie"),old.getString("csrf")));JSONObject bootstrap=api.json("GET","/api/bootstrap",null);old.put("data",bootstrap);store.settings(old);ui.post(this::render);});}catch(Exception e){error(e);}});Ui.secondary(this,refresh);refresh.setEnabled(!uploading&&!sealing);server.addView(refresh);}body.addView(server);
  LinearLayout info=Ui.card(this);info.addView(Ui.text(this,"Copia en el teléfono",18,Ui.INK));info.addView(Ui.text(this,"Archivos y metadatos se cifran con una clave propia del teléfono. La app conserva los registros después de enviarlos. Desinstalar la app o borrar sus datos elimina esa copia y su clave; envía primero los registros pendientes.",14,Ui.MUTED));info.addView(Ui.text(this,"Durante una grabación se utiliza un archivo temporal privado; se cifra al detener el video. Una grabación cortada antes de finalizar puede necesitar revisión.",13,Ui.MUTED));info.addView(Ui.text(this,"Identificador de instalación: "+settings.getString("installationId"),12,Ui.MUTED));Button panel=Ui.button(this,"Abrir panel web de prueba ↗",()->open(WEB));Ui.secondary(this,panel);info.addView(panel);body.addView(info);
 }
 private void chooseDemo(){try{JSONObject demo=Vault.demo(this);JSONArray users=demo.getJSONArray("users");String[] labels=new String[users.length()];for(int i=0;i<labels.length;i++){JSONObject u=users.getJSONObject(i);labels[i]=u.getString("name")+" · "+Policy.role(u.getString("role"));}new AlertDialog.Builder(this).setTitle("Usuario local de prueba").setItems(labels,(d,w)->{try{JSONObject next=store.settings();next.put("remote",false).put("demoUser",users.getJSONObject(w).getString("id")).remove("cookie");next.remove("csrf");next.remove("user");next.remove("data");store.settings(next);tab="capture";render();}catch(Exception e){error(e);}}).setNegativeButton("Cancelar",null).show();}catch(Exception e){error(e);}}
 private interface Task{void run()throws Exception;}
 private void network(Task task){if(uploading||sealing)return;progress.setText("Conectando…");io.execute(()->{try{task.run();ui.post(()->{if(progress!=null)progress.setText("");});}catch(Exception e){ui.post(()->{if(progress!=null)progress.setText("");error(e);});}});}
 private void open(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){error(e);}}
 private String shortId(String id){return id.substring(0,8);}
 private String format(String iso){try{return DateTimeFormatter.ofPattern("dd MMM yyyy · HH:mm:ss",Locale.forLanguageTag("es-MX")).withZone(ZoneId.of("America/Mexico_City")).format(Instant.parse(iso));}catch(Exception e){return iso;}}
 private String message(Exception e){return e.getMessage()==null?"No se pudo completar la operación. La copia local se conserva.":e.getMessage();}
 private void error(Exception e){notice("No se completó la operación",message(e));}
 private void notice(String title,String text){if(!isFinishing()&&!isDestroyed())new AlertDialog.Builder(this).setTitle(title).setMessage(text).setPositiveButton("Entendido",null).show();}
 private void fatal(Exception e){LinearLayout root=Ui.column(this);root.setPadding(Ui.dp(this,20),Ui.dp(this,30),Ui.dp(this,20),Ui.dp(this,20));root.addView(Ui.title(this,"No se pudo abrir la bóveda"));root.addView(Ui.text(this,message(e)+"\nNo borres los datos de la aplicación.",16,Ui.INK));Ui.root(this,root);}
 @Override protected void onPause(){flushNotes();super.onPause();}
 @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);io.shutdown();super.onDestroy();}
}
