package com.controlpublicidad.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.media.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;
import org.json.*;import java.io.*;import java.util.Locale;

/** Playback uses decrypted RAM, never an exported plaintext preview file. */
public final class PreviewActivity extends Activity {
 private RecordStore store;private JSONObject media;private MediaPlayer player;private TextureView texture;private boolean paused=false;private Surface surface;private Button play;
 @Override public void onCreate(Bundle state){super.onCreate(state);try{
  store=Vault.get(this);JSONObject record=store.record(getIntent().getStringExtra("recordId"));JSONObject settings=store.settings();if(!Vault.owner(settings).equals(record.getString("owner")))throw new IOException("La evidencia pertenece a otro perfil.");media=Policy.find(record.getJSONArray("media"),"id",getIntent().getStringExtra("mediaId"));if(media==null)throw new IOException("Archivo no disponible.");
  LinearLayout root=Ui.column(this),head=Ui.column(this);head.setPadding(Ui.dp(this,18),Ui.dp(this,8),Ui.dp(this,18),Ui.dp(this,8));head.addView(Ui.title(this,"photo".equals(media.getString("kind"))?"Fotografía":"Video"));head.addView(Ui.text(this,record.getString("campaignName"),15,Ui.INK));head.addView(Ui.text(this,media.getString("capturedAt"),12,Ui.MUTED));root.addView(head);
  if("photo".equals(media.getString("kind"))){ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setBackgroundColor(Color.BLACK);root.addView(image,new LinearLayout.LayoutParams(-1,0,1));new Thread(()->{try{byte[] bytes=store.files.read("media-"+media.getString("id")+".bin",12*1024*1024);BitmapFactory.Options opts=new BitmapFactory.Options();opts.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,opts);opts.inSampleSize=Math.max(1,Math.max(opts.outWidth,opts.outHeight)/1800);opts.inJustDecodeBounds=false;Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,opts);if(bitmap==null)throw new IOException("No se pudo abrir la fotografía.");
   ExifInterface exif=new ExifInterface(new ByteArrayInputStream(bytes));int o=exif.getAttributeInt(ExifInterface.TAG_ORIENTATION,ExifInterface.ORIENTATION_NORMAL);Matrix m=new Matrix();if(o==ExifInterface.ORIENTATION_ROTATE_90)m.postRotate(90);else if(o==ExifInterface.ORIENTATION_ROTATE_180)m.postRotate(180);else if(o==ExifInterface.ORIENTATION_ROTATE_270)m.postRotate(270);Bitmap shown=m.isIdentity()?bitmap:Bitmap.createBitmap(bitmap,0,0,bitmap.getWidth(),bitmap.getHeight(),m,true);runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())image.setImageBitmap(shown);});}catch(Exception e){runOnUiThread(()->error(e));}},"cp-preview").start();}
  else{texture=new TextureView(this);texture.setOpaque(true);root.addView(texture,new LinearLayout.LayoutParams(-1,0,1));texture.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){prepare(s);}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){resize();}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){release();return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});play=Ui.button(this,"Reproducir / pausar",()->{if(player!=null)try{if(player.isPlaying())player.pause();else player.start();}catch(Exception e){error(e);}});play.setEnabled(false);root.addView(play);}
  JSONObject gps=media.optJSONObject("gps");LinearLayout foot=Ui.column(this);foot.setPadding(Ui.dp(this,18),Ui.dp(this,8),Ui.dp(this,18),Ui.dp(this,8));if(gps==null)foot.addView(Ui.text(this,"GPS no disponible en esta toma",14,Ui.MUTED));else foot.addView(Ui.button(this,String.format(Locale.ROOT,"GPS · precisión ±%.0f m · abrir mapa ↗",gps.getDouble("accuracy")),()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/search/?api=1&query="+Uri.encode(gps.getDouble("lat")+","+gps.getDouble("lng")))));}catch(Exception e){error(e);}}));Button back=Ui.button(this,"Volver",this::finish);Ui.secondary(this,back);foot.addView(back);root.addView(foot);Ui.root(this,root);
 }catch(Exception e){error(e);}}
 private void prepare(SurfaceTexture s){new Thread(()->{try{byte[] bytes=store.files.read("media-"+media.getString("id")+".bin",50*1024*1024);runOnUiThread(()->{if(isFinishing()||paused)return;try{player=new MediaPlayer();surface=new Surface(s);player.setSurface(surface);player.setDataSource(new MediaDataSource(){public long getSize(){return bytes.length;}public int readAt(long pos,byte[] buffer,int offset,int size){if(pos>=bytes.length)return -1;if(pos<0)return -1;int n=(int)Math.min(size,bytes.length-pos);System.arraycopy(bytes,(int)pos,buffer,offset,n);return n;}public void close(){}});player.setOnPreparedListener(p->{resize();play.setEnabled(true);});player.setOnVideoSizeChangedListener((p,w,h)->resize());player.setOnErrorListener((p,what,extra)->{error(new IOException("No se pudo reproducir este video."));return true;});player.prepareAsync();}catch(Exception e){error(e);}});}catch(Exception e){runOnUiThread(()->error(e));}},"cp-video-preview").start();}
 private void resize(){if(texture==null||player==null)return;int vw=player.getVideoWidth(),vh=player.getVideoHeight(),tw=texture.getWidth(),th=texture.getHeight();if(vw<=0||vh<=0||tw<=0||th<=0)return;float ratio=vw/(float)vh,view=tw/(float)th;Matrix m=new Matrix();if(ratio>view)m.setScale(1,view/ratio,tw/2f,th/2f);else m.setScale(ratio/view,1,tw/2f,th/2f);texture.setTransform(m);}
 private void release(){if(player!=null){player.release();player=null;}if(surface!=null){surface.release();surface=null;}}
 private void error(Exception e){if(!isFinishing()&&!isDestroyed()&&!paused)new AlertDialog.Builder(this).setTitle("Evidencia conservada").setMessage(e.getMessage()==null?"No se pudo abrir el archivo.":e.getMessage()).setPositiveButton("Volver",(d,w)->finish()).show();}
 @Override protected void onResume(){super.onResume();paused=false;if(texture!=null&&texture.isAvailable()&&player==null)prepare(texture.getSurfaceTexture());}
 @Override protected void onPause(){paused=true;release();super.onPause();}
}
