package com.controlpublicidad.app;

import org.json.*;
import javax.crypto.*;
import java.io.*;
import java.nio.file.*;
import java.security.*;
import java.util.*;

public final class CoreTest {
 private static int assertions=0;
 private static void check(boolean condition,String message){assertions++;if(!condition)throw new AssertionError(message);}
 private interface Checked{void run()throws Exception;}
 private static void rejects(Checked fn,String message)throws Exception{boolean rejected=false;try{fn.run();}catch(Exception e){rejected=true;}check(rejected,message);}
 private static RecordStore fresh()throws Exception{KeyGenerator gen=KeyGenerator.getInstance("AES");gen.init(256);return new RecordStore(new CryptoFiles(Files.createTempDirectory("cp-android-test-").toFile(),gen.generateKey()));}
 private static JSONObject draft(RecordStore store,String owner)throws Exception{
  return store.create(owner,new JSONObject().put("id","sofia").put("name","Sofía").put("role","collaborator"),new JSONObject().put("id","cantera").put("name","Casa Cantera").put("types",new JSONArray().put("lona")),new JSONObject().put("id","member-sofia"),new JSONObject().put("installationId",UUID.randomUUID().toString()).put("name","Test").put("brand","Test").put("model","Test"));
 }
 private static JSONObject photo(RecordStore store,JSONObject r,byte[] bytes)throws Exception{return store.importPhoto(store.begin(r.getString("id"),"photo",new JSONObject().put("lat",19.7).put("lng",-101.2).put("accuracy",6).put("capturedAt",RecordStore.now())),bytes);}
 private static void crypto()throws Exception{
  RecordStore s=fresh();byte[] original="original evidencia GPS autor notas".getBytes("UTF-8");s.files.write("a.bin",original);byte[] encrypted1=Files.readAllBytes(s.files.file("a.bin").toPath());s.files.write("a.bin",original);byte[] encrypted2=Files.readAllBytes(s.files.file("a.bin").toPath());
  check(!Arrays.equals(encrypted1,encrypted2),"Every encryption must use a fresh IV");check(Arrays.equals(original,s.files.read("a.bin",1000)),"Lossless round trip");check(!new String(encrypted2,"ISO-8859-1").contains("original evidencia"),"No plaintext bytes on disk");
  Files.copy(s.files.file("a.bin").toPath(),s.files.file("b.bin").toPath());rejects(()->s.files.read("b.bin",1000),"AAD rejects file substitution");
  encrypted2[encrypted2.length-1]^=1;Files.write(s.files.file("a.bin").toPath(),encrypted2);rejects(()->s.files.read("a.bin",1000),"GCM rejects alteration");
  s.files.write("pending.bin",original);Files.move(s.files.file("pending.bin").toPath(),s.files.file("pending.bin.new").toPath());check(s.files.recoverWrite("pending.bin"),"Recover authenticated complete pre-rename write");check(Arrays.equals(original,s.files.read("pending.bin",1000)),"Recovered bytes match original");
  s.files.write("partial.bin",original);byte[] partial=Files.readAllBytes(s.files.file("partial.bin").toPath());Files.delete(s.files.file("partial.bin").toPath());Files.write(s.files.file("partial.bin.new").toPath(),Arrays.copyOf(partial,20));rejects(()->s.files.recoverWrite("partial.bin"),"Never promote incomplete ciphertext");check(!s.files.exists("partial.bin"),"No invalid replacement committed");
 }
 private static void records()throws Exception{
  RecordStore s=fresh();JSONObject r=draft(s,"test|sofia");String rid=r.getString("id");check(s.records("test|other").isEmpty(),"Profile isolation");rejects(()->s.update(rid,"barda",""),"Casa Cantera allows lona only");rejects(()->s.seal(rid),"Cannot seal empty draft");
  byte[] jpeg={-1,-40,-1,4,5,6};JSONObject m=photo(s,r,jpeg);check(m.getString("sha256").equals(CryptoFiles.hash(new ByteArrayInputStream(jpeg))),"Original hash preserved");check(m.getJSONObject("gps").getDouble("accuracy")==6,"Capture GPS preserved");
  // Crash after journal commit but before the record index commit.
  s.writeJson("record-"+rid+".json",r);s.recoverJournals();check(s.record(rid).getJSONArray("media").length()==1,"Replay capture journal");s.recoverJournals();check(s.record(rid).getJSONArray("media").length()==1,"Idempotent recovery");
  s.update(rid,"lona","Nota final");JSONObject sealed=s.seal(rid);String frozen=sealed.getJSONObject("manifest").toString();rejects(()->s.update(rid,"lona","cambiar"),"No edits after sealing");rejects(()->s.begin(rid,"photo",null),"No additions after sealing");
  // The sealed journal stays authoritative across a stale or missing record cache.
  s.writeJson("record-"+rid+".json",r);check(s.record(rid).getString("status").equals("pending"),"Recover seal even with stale cache");check(s.record(rid).getJSONObject("manifest").toString().equals(frozen),"Frozen seal survives stale cache");s.files.remove("record-"+rid+".json");check(s.records("test|sofia").size()==1,"Enumerate seal without cache");
  rejects(()->s.received(rid,new JSONObject().put("id",rid).put("status","uploading").put("number",1)),"Never claim incomplete upload");s.received(rid,new JSONObject().put("id",rid).put("status","synced").put("number",7));s.files.remove("record-"+rid+".json");check(s.record(rid).getInt("number")==7,"Durable receipt journal");check(Arrays.equals(jpeg,s.files.read("media-"+m.getString("id")+".bin",1000)),"Local original retained after receipt");
  for(String name:s.files.names())if(!name.endsWith(".new")){String bytes=new String(Files.readAllBytes(s.files.file(name).toPath()),"ISO-8859-1");check(!bytes.contains("Casa Cantera")&&!bytes.contains("Nota final"),"Metadata encrypted at rest");}
 }
 private static void limits()throws Exception{
  RecordStore s=fresh();JSONObject r=draft(s,"test|limits");for(int i=0;i<10;i++)photo(s,r,new byte[]{-1,-40,-1,1});rejects(()->s.begin(r.getString("id"),"photo",null),"Max 10 photos");
  for(int i=0;i<3;i++){JSONObject p=s.begin(r.getString("id"),"video",null);File raw=File.createTempFile("video-test-",".mp4");Files.write(raw.toPath(),new byte[]{0,0,0,0,102,116,121,112,1,2});s.importVideo(p,raw);raw.delete();}rejects(()->s.begin(r.getString("id"),"video",null),"Max 3 videos");check(s.seal(r.getString("id")).getJSONArray("media").length()==13,"Max mixed record accepted");
  RecordStore damaged=fresh();JSONObject d=draft(damaged,"test|damage");JSONObject m=photo(damaged,d,new byte[]{-1,-40,-1,1});byte[] bytes=Files.readAllBytes(damaged.files.file("media-"+m.getString("id")+".bin").toPath());bytes[20]^=1;Files.write(damaged.files.file("media-"+m.getString("id")+".bin").toPath(),bytes);rejects(()->damaged.seal(d.getString("id")),"Never seal corrupted copy");check(damaged.record(d.getString("id")).getString("status").equals("draft"),"Retain damaged draft without pretending sealed");
  RecordStore interrupted=fresh();JSONObject ir=draft(interrupted,"test|cut");JSONObject ip=interrupted.begin(ir.getString("id"),"video",null);interrupted.files.write("recovery-"+ip.getString("id")+".bin",new byte[]{1,2,3});interrupted.archiveInterrupted();check(interrupted.pending()==null,"Can continue after archiving interrupted capture");check(interrupted.files.exists("recovery-"+ip.getString("id")+".bin"),"Never delete interrupted original");check(interrupted.record(ir.getString("id")).getJSONArray("interrupted").length()==1,"Retain interrupted provenance");
 }
 private static void notes()throws Exception{
  RecordStore s=fresh();JSONObject r=draft(s,"local-test|sofia");String rid=r.getString("id");String value="Prueba de Sofía\nLona en fachada, revisión pendiente.";
  s.updateNotes(rid,value);RecordStore reopened=new RecordStore(s.files);check(value.equals(reopened.draft("local-test|sofia").getString("notes")),"Notes survive reopening the vault");
  photo(reopened,r,new byte[]{-1,-40,-1,1});check(value.equals(reopened.record(rid).getString("notes")),"Opening camera and attaching media retain notes");
  String finalNote=value+"\nSegunda revisión.";reopened.updateNotes(rid,finalNote);reopened.files.remove("record-"+rid+".json");reopened.recoverJournals();check(finalNote.equals(reopened.record(rid).getString("notes")),"Notes journal survives rebuilding from an older camera snapshot");
  JSONObject sealed=reopened.seal(rid);check(finalNote.equals(sealed.getString("notes")),"Sealed detail shows notes");check(finalNote.equals(sealed.getJSONObject("manifest").getString("notes")),"Upload manifest includes final notes");
  rejects(()->reopened.updateNotes(rid,"cambio"),"Sealed notes remain immutable");check(finalNote.equals(reopened.updateNotes(rid,finalNote).getString("notes")),"An unchanged lifecycle flush is safe after sealing");
  reopened.files.remove("record-"+rid+".json");reopened.writeJson("notes-"+rid+".json",new JSONObject().put("id",rid).put("notes","stale draft journal"));check(finalNote.equals(new RecordStore(s.files).record(rid).getString("notes")),"Sealed journal is authoritative over draft notes");
 }
 private static void teams()throws Exception{
  JSONObject seed=new JSONObject(new String(Files.readAllBytes(Paths.get("android/assets/demo.json")),"UTF-8"));RecordStore s=fresh();TeamStore teams=new TeamStore(s);JSONObject initial=teams.load(seed);JSONObject admin=Policy.find(initial.getJSONArray("users"),"id","a1"),leader=Policy.find(initial.getJSONArray("users"),"id","l1"),coord=Policy.find(initial.getJSONArray("users"),"id","c1"),sofia=Policy.find(initial.getJSONArray("users"),"id","f1");
  check(initial.getJSONArray("users").length()==10,"Preserve all ten original test profiles");check(Policy.assignments(initial,sofia,false).get(0).getJSONObject("campaign").getJSONArray("types").toString().equals("[\"lona\"]"),"Keep Sofia's original Casa Cantera lona-only assignment");
  JSONObject old=draft(s,"local-test|f1");String oldId=old.getString("id");old.put("notes","Nota guardada en 0.1.0");s.writeJson("record-"+oldId+".json",old);photo(s,old,new byte[]{-1,-40,-1,7});check("Nota guardada en 0.1.0".equals(s.record(oldId).getString("notes")),"Read notes saved before notes journals existed");String originalManifest=s.seal(oldId).getJSONObject("manifest").toString();
  JSONObject newLeader=teams.createUser(admin,new JSONObject().put("name"," Nuevo líder ").put("contact","Nuevo@Example.com").put("role","leader"));check(newLeader.getString("name").equals("Nuevo líder"),"Trim names");check(newLeader.getString("contact").equals("nuevo@example.com"),"Normalize contacts");
  rejects(()->teams.createUser(admin,new JSONObject().put("name","Duplicado").put("contact","NUEVO@example.com").put("role","leader")),"Reject case-insensitive duplicate contact");
  rejects(()->teams.createUser(admin,new JSONObject().put("name","Sin contacto").put("contact","123").put("role","leader")),"Reject invalid contact");
  rejects(()->teams.createUser(sofia,new JSONObject().put("name","Otro").put("contact","otro@example.com").put("role","leader")),"Collaborator cannot create users");
  rejects(()->teams.createUser(new JSONObject(sofia.toString()).put("role","admin"),new JSONObject().put("name","Falso").put("contact","falso@example.com").put("role","leader")),"Local persistence checks actual stored actor role");
  JSONObject input=new JSONObject().put("name","Campaña nueva").put("location","Morelia centro").put("leaderId",newLeader.getString("id")).put("types",new JSONArray().put("lona").put("barda"));
  rejects(()->teams.createCampaign(leader,input),"Leader cannot create a campaign");rejects(()->teams.createCampaign(admin,new JSONObject(input.toString()).put("types",new JSONArray())),"Campaign needs a permitted type");rejects(()->teams.createCampaign(admin,new JSONObject(input.toString()).put("types",new JSONArray().put("lona").put("lona"))),"Reject duplicate campaign types");rejects(()->teams.createCampaign(admin,new JSONObject(input.toString()).put("leaderId","c1")),"Campaign leader must have leader role");
  JSONObject campaign=teams.createCampaign(admin,input);String cid=campaign.getString("id");JSONObject saved=teams.load(seed);int leaders=0;JSONObject root=null;for(int i=0;i<saved.getJSONArray("memberships").length();i++){JSONObject m=saved.getJSONArray("memberships").getJSONObject(i);if(cid.equals(m.optString("campaignId"))&&"leader".equals(m.optString("role"))){leaders++;root=m;}}check(leaders==1&&root.isNull("parentId"),"Exactly one root leader per campaign");
  JSONObject coordinator=teams.createUser(newLeader,new JSONObject().put("name","Nueva coordinadora").put("contact","+52 (443) 123-4567").put("role","coordinator").put("campaignId",cid).put("parentId",root.getString("id")));check(coordinator.getString("contact").equals("+524431234567"),"Normalize mobile contact");
  saved=teams.load(seed);JSONObject parent=null;for(int i=0;i<saved.getJSONArray("memberships").length();i++){JSONObject m=saved.getJSONArray("memberships").getJSONObject(i);if(coordinator.getString("id").equals(m.getString("userId")))parent=m;}
  JSONObject collaborator=teams.createUser(coordinator,new JSONObject().put("name","Nuevo colaborador").put("contact","campo@example.com").put("role","collaborator").put("campaignId",cid).put("parentId",parent.getString("id")));
  rejects(()->teams.createUser(coord,new JSONObject().put("name","Ajeno").put("contact","ajeno@example.com").put("role","collaborator").put("campaignId",cid).put("parentId",parentId(teams.load(seed),coordinator.getString("id")))),"Coordinator cannot create in another coordinator's branch");
  rejects(()->teams.createUser(leader,new JSONObject().put("name","Rol incorrecto").put("contact","rol@example.com").put("role","collaborator").put("campaignId","p1").put("parentId","m2")),"Leader can create coordinators only");
  JSONObject reopened=new TeamStore(new RecordStore(s.files)).load(new JSONObject().put("users",new JSONArray()).put("campaigns",new JSONArray()).put("memberships",new JSONArray()));check(reopened.getJSONArray("users").length()==13,"New profiles survive restart and seed changes");check(reopened.getJSONArray("campaigns").length()==5,"New campaigns survive restart");check(TeamPolicy.scoped(reopened,coordinator).size()==2,"Coordinator sees only own branch");check(TeamPolicy.scoped(reopened,newLeader).size()==3,"Leader sees own team only");
  List<JSONObject> assignments=Policy.assignments(reopened,collaborator,false);check(assignments.size()==1&&assignments.get(0).getJSONObject("campaign").getJSONArray("types").length()==2,"New collaborator captures only assigned mixed campaign types");
  String before=reopened.toString();rejects(()->teams.createCampaign(admin,new JSONObject(input.toString()).put("location","")),"Reject empty location");check(teams.load(seed).toString().equals(before),"Invalid create makes no partial changes");
  String encrypted=new String(Files.readAllBytes(s.files.file("local-teams.json").toPath()),"ISO-8859-1");check(!encrypted.contains("campo@example.com")&&!encrypted.contains("Campaña nueva"),"Users and campaigns are encrypted on disk");
  check(s.records("local-test|f1").size()==1&&s.record(oldId).getJSONObject("manifest").toString().equals(originalManifest),"Administration and migration preserve existing immutable evidence");
  JSONObject inactive=new JSONObject(reopened.toString());Policy.find(inactive.getJSONArray("memberships"),"id",parentId(inactive,coordinator.getString("id"))).put("status","inactive");check(TeamPolicy.parents(inactive,admin,"collaborator",false).stream().noneMatch(m->cid.equals(m.optString("campaignId"))),"Cannot create below an inactive parent");
 }
 private static String parentId(JSONObject data,String uid)throws Exception{JSONArray members=data.getJSONArray("memberships");for(int i=0;i<members.length();i++){JSONObject m=members.getJSONObject(i);if(uid.equals(m.getString("userId")))return m.getString("id");}throw new IOException("Missing test member");}
 private static void policy()throws Exception{
  JSONObject actor=new JSONObject().put("id","sofia").put("role","collaborator"),leader=new JSONObject().put("id","l").put("campaignId","c").put("userId","mariana").put("role","leader").put("parentId",JSONObject.NULL).put("status","active");JSONObject coord=new JSONObject().put("id","d").put("campaignId","c").put("userId","diego").put("role","coordinator").put("parentId","l").put("status","active");JSONObject child=new JSONObject().put("id","s").put("campaignId","c").put("userId","sofia").put("role","collaborator").put("parentId","d").put("status","active");
  JSONObject data=new JSONObject().put("memberships",new JSONArray().put(leader).put(coord).put(child)).put("campaigns",new JSONArray().put(new JSONObject().put("id","c").put("status","active").put("types",new JSONArray().put("lona"))));check(Policy.assignments(data,actor,false).size()==1,"Active own branch captures");coord.put("status","inactive");check(Policy.assignments(data,actor,false).isEmpty(),"Inactive parent blocks local capture");coord.put("status","active");leader.put("parentId","d");check(Policy.assignments(data,actor,false).isEmpty(),"Reject ancestry cycle");leader.put("parentId",JSONObject.NULL);
  data.put("memberships",new JSONArray().put(child));check(Policy.assignments(data,actor,true).isEmpty(),"Remote must fail closed without server eligibility");data.put("captureAssignments",new JSONArray().put(new JSONObject().put("membershipId","s").put("campaignId","c")));check(Policy.assignments(data,actor,true).size()==1,"Remote own eligibility without parent data leakage");actor.put("id","other");check(Policy.assignments(data,actor,true).isEmpty(),"Remote assignment never authorizes another person");rejects(()->new ApiClient.HttpTransport("http://example.com","",""),"No plaintext HTTP");rejects(()->new ApiClient.HttpTransport("https://user:password@example.com","",""),"No embedded URL credentials");
 }
 private static final class MockServer implements ApiClient.Transport{
  final int chunk=256*1024;JSONObject manifest;final Map<Integer,byte[]> pieces=new TreeMap<>();boolean cut=true;int puts=0;final String mid;MockServer(String mid){this.mid=mid;}
  public JSONObject request(String method,String path,byte[] body,String ct)throws Exception{
   if(method.equals("POST")&&path.equals("/api/records")){JSONObject input=new JSONObject(new String(body,"UTF-8"));if(manifest!=null)check(manifest.toString().equals(input.toString()),"Retries keep the identical manifest");manifest=input;JSONArray received=new JSONArray();for(int k:pieces.keySet())received.put(k);return new JSONObject().put("id",manifest.getString("id")).put("status","uploading").put("chunkBytes",chunk).put("media",new JSONArray().put(new JSONObject().put("id",mid).put("received",received)));}
   if(method.equals("PUT")){int index=Integer.parseInt(path.substring(path.lastIndexOf('/')+1));if(index==1&&cut){cut=false;throw new IOException("Network cut");}check(!pieces.containsKey(index),"Retry skips received chunks");pieces.put(index,body);puts++;return new JSONObject();}
   if(path.endsWith("/finalize")){ByteArrayOutputStream all=new ByteArrayOutputStream();for(byte[] bytes:pieces.values())all.write(bytes);check(CryptoFiles.hash(new ByteArrayInputStream(all.toByteArray())).equals(manifest.getJSONArray("media").getJSONObject(0).getString("sha256")),"Server sees identical original bytes");return new JSONObject().put("id",manifest.getString("id")).put("status","synced").put("number",1);}
   throw new IOException("Unexpected route");
  }
 }
 private static void upload()throws Exception{
  RecordStore s=fresh();JSONObject r=draft(s,"test|upload");byte[] bytes=new byte[700_000];new SecureRandom().nextBytes(bytes);bytes[0]=-1;bytes[1]=-40;bytes[2]=-1;JSONObject m=photo(s,r,bytes);JSONObject sealed=s.seal(r.getString("id"));MockServer remote=new MockServer(m.getString("id"));ApiClient client=new ApiClient(remote);
  rejects(()->client.upload(s,sealed,t->{}),"Interrupted upload remains pending");check(s.record(r.getString("id")).getString("status").equals("pending"),"No false confirmed state after network loss");check(remote.pieces.size()==1,"One chunk accepted before loss");JSONObject receipt=client.upload(s,sealed,t->{});s.received(r.getString("id"),receipt);check(remote.puts==3,"Only missing fragments retried");check(s.record(r.getString("id")).getString("status").equals("synced"),"Complete receipt marks synced");check(Arrays.equals(bytes,s.files.read("media-"+m.getString("id")+".bin",800_000)),"Never remove original after sync");
 }
 public static void main(String[] args)throws Exception{crypto();records();notes();limits();policy();teams();upload();System.out.println("Android core: "+assertions+" assertions passed (JVM; hardware and Android Keystore require device validation).");}
}
